apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - image: jmezna/orders:0.7
        name: order
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: gcloud
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_SERVER_BASEURL
            value: http://159.122.179.214:32682
          - name: KUMULUZEE_DATASOURCES0_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pg-pass
                key: KUMULUZEE_DATASOURCES0_PASSWORD
        ports:
        - containerPort: 8081
          name: server
          protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: order
spec:
  type: LoadBalancer
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: order
